### ISSUE TITLE
Support for Town Colors (different from Nation Colors)

### ISSUE THREAD

**Issue by 0xBit-MC** [TownyAdvanced/Pl3xMap-Towny#11]
**Describe the solution you'd like**
Support for the new Town Color option in Towny; 

**Additional context**
Towny has added Town Colors, the inner color of an area is the Town Color but the bold border outlining the town is related to the nation color.

**Comment by silverwolfg11** [comment]
This feature has been implemented in release [v1.0.0](https://github.com/TownyAdvanced/Pl3xMap-Towny/releases/tag/v1.0.0). Thank you for request!
