### ISSUE TITLE
Compatibility With Squaremap

### ISSUE THREAD

**Issue by Ashparty** [TownyAdvanced/Pl3xMap-Towny#15]
**Is your feature request related to a problem? Please describe.**

As pl3xmap is now coming to a close, can we have functionality with Squaremap  (https://github.com/jpenilla/squaremap/tree/release) which happens to be a Pl3xmap fork, which already has compatibility with Pl3xmap-Markers
**Describe the solution you'd like**

Update the plugin to work with Squaremap

**Describe alternatives you've considered**

I have not found any alternatives to Pl3xmap for 1.18 besides squaremap
**Additional context**

**Comment by silverwolfg11** [comment]
I can take a look at implementing support for this, however since it's not a straight fork (meaning that the plugin name and API name is not the same), it might be a while before I have time to implement support for this.

**Comment by SmallSansSerif** [comment]
Adding my name to the list for interest in this.

**Comment by ar00n** [comment]
https://github.com/ar00n/squaremap-Towny/releases thank me later xo @Isus104 @SmallSansSerif @Ashparty

**Comment by silverwolfg11** [comment]
If you are using a Pl3xMap soft-fork or squaremap, please use version [2.0.0-BETA-1](https://github.com/TownyAdvanced/Pl3xMap-Towny/releases/tag/v2.0.0-BETA-1).
